language: python
python:
    - "3.6"
    
before_script:
  - psql -c "CREATE DATABASE maintenancetracker;" -U postgres
 
install:
    - pip install -r requirements.txt
    - pip install coveralls
script:
    - nosetests api/tests/*
# run coverage tests
after_success:
  - coveralls
